// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsGfHQShP2NT6vhKe80E4OB8TDPa7vufw',
    appId: '1:397688306643:web:9c7dcd09774289aea38d26',
    messagingSenderId: '397688306643',
    projectId: 'marine-safe-app',
    authDomain: 'marine-safe-app.firebaseapp.com',
    storageBucket: 'marine-safe-app.firebasestorage.app',
    measurementId: 'G-LK229L6K60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaZBl-Fdi3LqBcHn7RjKg5Tag6iEjcDeA',
    appId: '1:397688306643:android:55a4370a478ec9c1a38d26',
    messagingSenderId: '397688306643',
    projectId: 'marine-safe-app',
    storageBucket: 'marine-safe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP2HFSrV81j-HRmoJnAQ7rf9PE81yfzWg',
    appId: '1:397688306643:ios:a0c63342a196e170a38d26',
    messagingSenderId: '397688306643',
    projectId: 'marine-safe-app',
    storageBucket: 'marine-safe-app.firebasestorage.app',
    iosBundleId: 'com.example.marineSafeNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP2HFSrV81j-HRmoJnAQ7rf9PE81yfzWg',
    appId: '1:397688306643:ios:a0c63342a196e170a38d26',
    messagingSenderId: '397688306643',
    projectId: 'marine-safe-app',
    storageBucket: 'marine-safe-app.firebasestorage.app',
    iosBundleId: 'com.example.marineSafeNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsGfHQShP2NT6vhKe80E4OB8TDPa7vufw',
    appId: '1:397688306643:web:cb5dc0fb55b2da22a38d26',
    messagingSenderId: '397688306643',
    projectId: 'marine-safe-app',
    authDomain: 'marine-safe-app.firebaseapp.com',
    storageBucket: 'marine-safe-app.firebasestorage.app',
    measurementId: 'G-G5FZRKW5P9',
  );
}
